source 'http://rubygems.org'

gem 'rails', '3.2.9'

gem 'sqlite3'
gem 'inherited_resources'

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'

group :test do
  gem 'json_spec'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'rspec_api_documentation', :path => "../"
  gem 'raddocs', '0.1.0'
  gem 'debugger'
end
